# Generated by Django 5.2.1 on 2025-05-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=10)),
                ('coursename', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
            ],
        ),
    ]
